config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  post 'layouts/ajax_save'
  post 'layouts/ajax_save_values'
  get 'layouts/ajax_load'

  get 'notes/train'
  get 'notes/ajax_get_variables'
  post 'notes/ajax_new'
  post 'notes/ajax_update'

  get 'components/ajax_modal'

  resources :layouts,    only: [:new, :destroy, :update, :edit, :show]
  resources :notes,      only: [:index, :destroy]
  resources :components, only: [:update]

  root 'layouts#show'
end

app/models/layout.rb
class Layout < ApplicationRecord
  belongs_to :user
  has_many :components, :dependent => :destroy

  def self.get_current_layout(user)
    if !user.layout.nil? and Layout.exists? id: user.layout
      return Layout.find(user.layout)
    else
      if Layout.exists? user_id: user.id
        layout = Layout.where(user_id: user.id).first
        User.update(user.id, layout: layout.id)
        return layout
      else
        return self.get_default_layout(user)
      end
    end
  end

  def self.get_default_layout(user)
    if Layout.exists? user_id: user.id, name: 'default'
      layout = Layout.where(user_id: user.id, name: 'default').first
      User.update(user.id, layout: layout.id)
      return layout
    else
      layout = Layout.create(
        user_id: user.id,
        name: 'default'
      )
      User.update(user.id, layout: layout.id)
      return layout
    end
  end

  def self.create_new_layout(user, name)
    if name != nil and name != ''
      if Layout.exists? user_id: user.id, name: name
        User.update(user.id,
          layout: Layout.where(user_id: user.id, name: name).first.id 
        )
      else
        new_layout = Layout.create(user_id: user.id, name: name)
        User.update(user.id, layout: new_layout.id)
      end
    end
  end

  def self.save_layout(user, data)
    layout = Layout.find(user.layout)
    for d in data
      Component.update_record(layout, d)
    end
  end

  def self.save_values(user, data)
    layout = Layout.find(user.layout)
    for d in data
      Component.update_value(layout, d)
    end
  end

end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
  before_action :authenticate_user!
  before_action :un_pause

  def show
    @user = User.find(current_user.id)
    @user_name = User.user_name(@user)
    @layout = Layout.get_current_layout(@user)
    @layouts = Layout.where(user_id: @user.id)
  end

  def edit
    @user = User.find(current_user.id)
    @user_name = User.user_name(@user)
    @layout = Layout.find(params[:id])
  end

  def new
    Layout.create_new_layout(current_user, params[:name])
    redirect_to root_path
  end

  def destroy
    Layout.find(params[:id]).destroy
    Layout.get_current_layout(current_user)
    redirect_to root_path
  end

  def update
    User.update(current_user.id, layout: params[:id])
    redirect_to root_path
  end

  def ajax_save_values
    Layout.save_values current_user, JSON.parse(params[:data])
    return 0
  end

  def ajax_save
    Layout.save_layout current_user, JSON.parse(params[:data])
    return 0
  end

  def ajax_load
    render json: get_layout
  end

  private
    def get_layout
      layout_id = Layout.find(current_user.layout).id
      return Component.where(layout_id: layout_id)
    end

    def un_pause
      if $REDIS.exists('pause') and $REDIS.get('pause').to_i == current_user.id
        $REDIS.del('pause')
      end
    end

end

app/helpers/layout_helper.rb
module LayoutHelper
end

app/views/layouts/_layout_properties_modal.html.erb
<!-- Modal -->
<div class="modal fade text-body" id="layoutPropertiesModal" tabindex="-1" role="dialog" aria-labelledby="layoutPropertiesModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="layoutPropertiesModalLabel">Layout Properties</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"
          data-toggle="collapse" data-target="#navbarSupportedContent" >Cancel</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal"
          data-toggle="collapse" data-target="#navbarSupportedContent" >Save</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar_edit.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#"><strong><%= user_name %></strong>: <%= current_layout.name %>: <strong>EDIT</strong></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown">
          +Add Item
        </a>
        <div id="dropdown_component_list" class="dropdown-menu"></div>
      </li>

      <li id="link_item_prop" class="nav-item" hidden>
        <a class="nav-link" href="javascript:void(0)">Item Properties </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" data-toggle="modal" data-target="#layoutPropertiesModal">Layout Properties </a>
      </li>
      <li class="nav-item">
        <%= link_to 'Edit Variables', notes_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%#<a class=" nav-link " href="javascript:void(0)">Train</a>%>
        <%= link_to 'Train Variables', notes_train_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Save Layout', current_layout, onclick: "GUI.save_layout()", class: 'nav-link' %>
      </li>
      <li class="nav-divider">
        <a>-------------------</a>
      </li>
      <li class="nav-item">
        <%= link_to 'Cancel', current_layout, class: 'nav-link' %>
      </li>
    </ul>
  </div>

</nav>

<%= render 'layout_properties_modal',
  current_layout: current_layout %>

app/views/layouts/_navbar_show.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a id="brand_link" class="navbar-brand badge-holder" href="javascript:void(0)" onclick="JS.Layouts.Show.Reset()">
    <strong><%= user_name %></strong>: <%= current_layout.name %>
    <span id="dirty_levels" class="badge badge-pill badge-danger" hidden>*</span>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          href="javascript:void()"
          onclick="GUI.save_values()">Save Values </a>
      </li>
      <li class="nav-item">
        <%= link_to 'Edit', edit_layout_path(current_layout), class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Remove ', current_layout, method: :delete,
          data: { confirm: "Are you sure you want to permanently remove this layout?" },
          class: 'nav-link' %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Load 
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% for layout in layouts %>
            <%= link_to layout.name, layout_path(layout), method: :put, class: 'dropdown-item' %>
          <% end %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="javascript:void()" data-toggle="modal", data-target="#newLayoutModal">New </a>
        </div>
      </li>
      <li class=" nav-item ">
        <%= link_to 'Switch User', destroy_user_session_path, method: :delete,
          data: { confirm: "Are you sure you want to switch users?" }, class: " nav-link "%>
      </li>
    </ul>
  </div>

</nav>

<!-- Modal -->
<div class="modal fade text-body" id="newLayoutModal" tabindex="-1" role="dialog" aria-labelledby="newLayoutModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newLayoutModalLabel">New Layout Name</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_tag new_layout_path, method: 'get' do %>
        <div class="modal-body">
          <%= text_field_tag :name, '', placeholder: 'default',  class: 'form-control' %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= submit_tag :Create, class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class=" text-light ">
    <script>JS.user_id = <%= current_user.present? ? current_user.id : 0 %></script>
    <%= yield %>
  </body>
</html>

app/views/layouts/edit.html.erb
<%= render 'navbar_edit',
  user_name: @user_name,
  current_layout: @layout %>

<div class=" container text-center fill-all " >
  <div id="wrap_gui" class=" row fill-all " >
    <div id="wrap" class=" col m-0 p-0 ">an error occurred.. </div>
  </div>
</div>

<!-- container for component property modals -->
<div id="componentModalBody"></div>

<script>JS.Layouts.Edit.onLoad(<%= @layout.id %>)</script>

app/views/layouts/show.html.erb
<%= render 'navbar_show',
  user_name: @user_name,
  current_layout: @layout,
  layouts: @layouts %>

<div class=" container text-center fill-all " >
  <div id="wrap_gui" class=" row fill-all " >
    <div id="wrap" class=" col m-0 p-0 ">an error occurred.. </div>
  </div>
</div>

<script>JS.Layouts.Show.onLoad()</script>